In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [7]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape(-1, 1)
print(x,x.shape,sep = '\n')

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
(6, 1)


In [8]:
y = np.array([5, 20, 14, 32, 22, 38])
y

array([ 5, 20, 14, 32, 22, 38])

In [9]:
model = LinearRegression()
model.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
r_sq = model.score(x,y)
print("Coefficient of determination:",r_sq)

Coefficient of determination: 0.715875613747954


In [12]:
print("Intercept is :",model.intercept_)

Intercept is : 5.633333333333329


In [14]:
print("Slope is :",model.coef_)

Slope is : [0.54]


In [15]:
y_pred = model.predict(x)

In [16]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [17]:
y_pred = model.intercept_ + model.coef_ * x

In [18]:
print('predicted response:', y_pred, sep='\n') # to cross check with the earlier predicted responses

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [21]:
from sklearn.metrics import mean_squared_error

In [22]:
mean_squared_error(y, y_pred)

33.75555555555556

In [ ]:
# new inputs

In [24]:
x_new = np.arange(5).reshape((-1, 1))
x_new

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [25]:
y_new = model.predict(x_new)
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
